apiVersion: apps/v1
kind: Service
metadata:
  name: helloworld
  labels:
    app: helloworld
    tier: backend
spec:
  type: NodePort
  ports:
    # the port that this service should serve on
  - port: 8080
  selector:
    app: helloworld
    tier: backend

